# Generated by Django 4.1.4 on 2023-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip_planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(name="Activity",),
        migrations.DeleteModel(name="Trip",),
    ]
