# Generated by Django 4.1.3 on 2023-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherforecast_lat_weatherforecast_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
