# Generated by Django 4.1.3 on 2023-08-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherforecast_rainfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
