# Generated by Django 4.1.3 on 2023-08-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weatherforecast_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='humidity',
            field=models.FloatField(default=0),
        ),
    ]
